export const USER_REQUEST_TYPES = {
    GET_ALL_REQUEST_START: "GET_ALL_REQUEST_START",
    GET_ALL_REQUEST_SUCCESS: "GET_ALL_REQUEST_SUCCESS",
    GET_ALL_REQUEST_FAILURE: "GET_ALL_REQUEST_FAILURE",
};
  