export const USER_REQUEST_TYPES = {
  GET_ALL_RERQUEST_START: "GET_ALL_RERQUEST_START",
  GET_ALL_RERQUEST_SUCCESS: "GET_ALL_RERQUEST_SUCCESS",
  GET_ALL_RERQUEST_FAILURE: "GET_ALL_RERQUEST_FAILURE",
};
